"""added_relationships

Revision ID: 3fb7e956847e
Revises: 11accb2f989a
Create Date: 2026-03-06 19:40:12.136966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb7e956847e'
down_revision: Union[str, Sequence[str], None] = '11accb2f989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sales', 'user_id')
    # ### end Alembic commands ###
